spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  security:
    user:
      name: dhiraj
      password: Dhiraj@1234

server:
  port: 8080
